//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HongDucStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class BaiViet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiViet()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
        }
    
        public int MaBaiViet { get; set; }
        public string TenBaiViet { get; set; }
        public string MoTaNgan { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> XetDuyet { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public string HinhAnh { get; set; }

        public HttpPostedFileBase imagePost { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
    }
}
