//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HongDucStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatHang()
        {
            this.DatHangChiTiet = new HashSet<DatHangChiTiet>();
        }
    
        public int MaDatHang { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> MaChiNhanh { get; set; }
        public string ThoiGianNhanHang { get; set; }
        public string HoTenNguoiNhan { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<int> TinhTrangDonHang { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHangChiTiet> DatHangChiTiet { get; set; }
    }
}
