//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HongDucStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class LienHeBanXe
    {
        public int MaLienHe { get; set; }
        public string HoVaTen { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string TenXe { get; set; }
        public string NamSanXuat { get; set; }
        public string MoTaXe { get; set; }
        public string HinhAnhXe { get; set; }
        public HttpPostedFileBase imageProduct { get;set;}
        public Nullable<int> GiaTienMuonBan { get; set; }
    }
}
