//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HongDucStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class MauSac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MauSac()
        {
            this.DatHangChiTiet = new HashSet<DatHangChiTiet>();
        }
    
        public int MaMau { get; set; }
        public string TenMau { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> Delta { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> isCheck { get; set; }
        public int MaSanPham { get; set; }

        public HttpPostedFileBase imageProductColor { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHangChiTiet> DatHangChiTiet { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
