//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HongDucStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
            this.DatHangChiTiet = new HashSet<DatHangChiTiet>();
            this.MauSac = new HashSet<MauSac>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> GiaGiam { get; set; }
        public Nullable<int> TinhTrangXe { get; set; }
        public string MoTa { get; set; }
        public string KhuyenMai { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> MaChiNhanh { get; set; }
        public Nullable<int> MaHang { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public Nullable<int> MaNhanVien { get; set; }

        public HttpPostedFileBase imageProduct { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        public virtual ChiNhanh ChiNhanh { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHangChiTiet> DatHangChiTiet { get; set; }
        public virtual HangXe HangXe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MauSac> MauSac { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
